/*
Generated by DB-Lens PlanPatch. Human approval required.
Baseline planner cost: 4107.00
Optimized planner cost: 77.76
Estimated cost reduction: 98.11%
Virtual index used: yes
WARNING: CREATE INDEX CONCURRENTLY cannot run inside a transaction block.
*/
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_pp_orders_customer_id_b389ec"
    ON "public"."orders" ("customer_id");
