-- Generated by DB-Lens PlanPatch. Human approval required.
-- WARNING: DROP INDEX CONCURRENTLY cannot run inside a transaction block.
DROP INDEX CONCURRENTLY IF EXISTS "public"."idx_pp_orders_customer_id_b389ec";
