"""Deterministic, reversible SQL migration generation for PlanPatch."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
import hashlib
import math
import os
from pathlib import Path
import re
import tempfile

from planpatch.planner import MIN_COST_REDUCTION_PCT, PlanEvidence


POSTGRES_IDENTIFIER_MAX_BYTES = 63
_INDEX_PREFIX = "idx_pp_"
_SAFE_NAME_COMPONENT = re.compile(r"[^a-z0-9_]+")


@dataclass(frozen=True, slots=True)
class MigrationArtifact:
    """Generated up/down migration files for one index recommendation."""

    up_sql_path: Path
    down_sql_path: Path
    up_sql_content: str
    index_name: str


class MigrationError(ValueError):
    """Raised when a safe migration artifact cannot be generated."""


def generate_migration(
    table_name: str,
    column_name: str,
    evidence: PlanEvidence,
    output_dir: str,
) -> MigrationArtifact:
    """Generate deterministic concurrent-index migration files atomically."""
    _validate_inputs(table_name, column_name, evidence, output_dir)

    relation_parts = _split_qualified_identifier(table_name)
    digest = hashlib.sha256(
        f"{table_name}\0{column_name}".encode("utf-8")
    ).hexdigest()[:6]
    index_name = _build_index_name(
        table_component=relation_parts[-1],
        column_component=column_name,
        digest=digest,
    )

    quoted_table = ".".join(_quote_identifier(part) for part in relation_parts)
    quoted_column = _quote_identifier(column_name)
    quoted_index = _quote_identifier(index_name)
    index_relation = ".".join(
        (*(_quote_identifier(part) for part in relation_parts[:-1]), quoted_index)
    )

    up_sql_content = _build_up_sql(
        quoted_table=quoted_table,
        quoted_column=quoted_column,
        quoted_index=quoted_index,
        evidence=evidence,
    )
    down_sql_content = (
        "-- Generated by DB-Lens PlanPatch. Human approval required.\n"
        "-- WARNING: DROP INDEX CONCURRENTLY cannot run inside a transaction block.\n"
        f"DROP INDEX CONCURRENTLY IF EXISTS {index_relation};\n"
    )

    destination = Path(output_dir).expanduser()
    try:
        destination.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise MigrationError("output_directory_creation_failed") from exc
    if not destination.is_dir():
        raise MigrationError("output_dir_is_not_a_directory")

    date_prefix = datetime.now(UTC).strftime("%Y%m%d")
    basename = f"{date_prefix}_add_{index_name}"
    up_sql_path = destination / f"{basename}.sql"
    down_sql_path = destination / f"{basename}.down.sql"

    _atomic_write_text(up_sql_path, up_sql_content)
    _atomic_write_text(down_sql_path, down_sql_content)

    return MigrationArtifact(
        up_sql_path=up_sql_path,
        down_sql_path=down_sql_path,
        up_sql_content=up_sql_content,
        index_name=index_name,
    )


def _validate_inputs(
    table_name: str,
    column_name: str,
    evidence: PlanEvidence,
    output_dir: str,
) -> None:
    if not table_name.strip():
        raise MigrationError("invalid_table_name")
    if not column_name.strip():
        raise MigrationError("invalid_column_name")
    if not output_dir.strip():
        raise MigrationError("invalid_output_directory")

    costs = (
        evidence.baseline_cost,
        evidence.optimized_cost,
        evidence.cost_reduction_pct,
    )
    if not all(math.isfinite(value) for value in costs):
        raise MigrationError("invalid_plan_evidence")
    if evidence.baseline_cost <= 0.0 or evidence.optimized_cost < 0.0:
        raise MigrationError("invalid_plan_evidence")
    if (
        not evidence.is_viable
        or not evidence.used_virtual_index
        or evidence.cost_reduction_pct < MIN_COST_REDUCTION_PCT
    ):
        raise MigrationError("non_viable_plan_evidence")


def _build_index_name(
    *,
    table_component: str,
    column_component: str,
    digest: str,
) -> str:
    table_slug = _slugify(table_component)
    column_slug = _slugify(column_component)
    fixed_bytes = len(_INDEX_PREFIX) + len(digest) + 2
    component_budget = POSTGRES_IDENTIFIER_MAX_BYTES - fixed_bytes

    table_budget = min(len(table_slug), component_budget // 2)
    column_budget = min(len(column_slug), component_budget - table_budget)
    table_budget = min(
        len(table_slug),
        table_budget + component_budget - table_budget - column_budget,
    )

    index_name = (
        f"{_INDEX_PREFIX}{table_slug[:table_budget]}_"
        f"{column_slug[:column_budget]}_{digest}"
    )
    if len(index_name.encode("ascii")) > POSTGRES_IDENTIFIER_MAX_BYTES:
        raise MigrationError("index_name_too_long")
    return index_name


def _slugify(value: str) -> str:
    slug = _SAFE_NAME_COMPONENT.sub("_", value.lower()).strip("_")
    if not slug:
        raise MigrationError("identifier_has_no_safe_characters")
    return slug


def _build_up_sql(
    *,
    quoted_table: str,
    quoted_column: str,
    quoted_index: str,
    evidence: PlanEvidence,
) -> str:
    return (
        "/*\n"
        "Generated by DB-Lens PlanPatch. Human approval required.\n"
        f"Baseline planner cost: {evidence.baseline_cost:.2f}\n"
        f"Optimized planner cost: {evidence.optimized_cost:.2f}\n"
        f"Estimated cost reduction: {evidence.cost_reduction_pct:.2f}%\n"
        f"Virtual index used: {'yes' if evidence.used_virtual_index else 'no'}\n"
        "WARNING: CREATE INDEX CONCURRENTLY cannot run inside a transaction block.\n"
        "*/\n"
        f"CREATE INDEX CONCURRENTLY IF NOT EXISTS {quoted_index}\n"
        f"    ON {quoted_table} ({quoted_column});\n"
    )


def _quote_identifier(value: str) -> str:
    if not value or "\x00" in value:
        raise MigrationError("invalid_sql_identifier")
    escaped = value.replace('"', '""')
    return f'"{escaped}"'


def _split_qualified_identifier(identifier: str) -> tuple[str, ...]:
    parts: list[str] = []
    current: list[str] = []
    quoted = False
    index = 0

    while index < len(identifier):
        character = identifier[index]
        if character == '"':
            if quoted and index + 1 < len(identifier) and identifier[index + 1] == '"':
                current.append('"')
                index += 2
                continue
            quoted = not quoted
        elif character == "." and not quoted:
            parts.append("".join(current))
            current = []
        else:
            current.append(character)
        index += 1

    if quoted:
        raise MigrationError("invalid_table_identifier")
    parts.append("".join(current))
    if not 1 <= len(parts) <= 2 or any(not part for part in parts):
        raise MigrationError("invalid_table_identifier")
    return tuple(parts)


def _atomic_write_text(path: Path, content: str) -> None:
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary_file:
            temporary_path = Path(temporary_file.name)
            temporary_file.write(content)
            temporary_file.flush()
            os.fsync(temporary_file.fileno())
        os.replace(temporary_path, path)
    except OSError as exc:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)
        raise MigrationError(f"migration_write_failed: {path}") from exc
